edition = "2024"
fn_params_layout = "Compressed"
newline_style = "Unix"
use_small_heuristics = "Max"
max_width = 100
use_field_init_shorthand = true
#indent_style = "Visual"
#preserve_block_start_blank_lines=true
#imports_granularity = "Crate"
#group_imports = "StdExternalCrate"
#overflow_delimited_expr = true
